development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_dev
  pool: 5
  username: shaun

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: shaun